composer.json
HHVM reports itself as having an extension named "xhp" (``hhvm --php -r "var_dump(extension_loaded('xhp'));"`` => ``bool(true)``), so tell composer to check for that when trying to install this package. If this repo ever gets hackified, then this can change to ``hhvm`` instead of ``ext-xhp``.
=> Add a requires section to composer.json.

composer.json
Since hack is required, hhvm should be required, not the xhp php extension
=> Changed ext-xhp requirement to hhvm, fixes #102

src/core.php
Adds support for generators inside XHP rendering. This makes one very important change to basic XHP principles, and that is that the rendering order can no longer be guaranteed. Previously, XHP would follow a breadth-first rendering from `:x:element` to `:x:primitive` (concurrently), but with this change, XHP will now render depth-first in search of `WaitHandle`s, batching together as many as it can. Additionally, all `:x:elements` will be rendered before the `:x:primitive` pass will begin. In theory this should have no affect because XHP does not store or encourage storing of references to other XHP elements (besides the parent, which still will be guaranteed to be rendered first). However, it is still possible to manually keep references and a variable rendering order has the potential …
=> Add Support for Awaitable XHP

composer.json
As dev-hack's going to be turning into 2.x, would be nice to be able to use "~2" as a version requirement already. This basically has composer treat the hack branch as if it were name 2 instead.
=> Alias dev-hack to 2.x-dev

.travis.yml
Requires someone with the right permissions on the repo to add it to travis-ci.org as well.
Once facebook/hhvm#4934 is fixed, just remove the `matrix` section to have failures on hhvm-nightly cause the build to fail.
Example run: https://travis-ci.org/simonwelsh/xhp/builds/53095054
=> Enable travis

tests/AttributesCoercionModeTest.php
Found this since I've got [this hhi file](https://git.simon.geek.nz/91-carriage/xhp-foundation/blob/master/tests/definitions.hhi) so that I can have everything in xhp-foundation as strict.
=> Correct case of assertSame

src/core/ComposableElement.php, src/core/ReflectionXHPAttribute.php
- stricter typing
- fewer array casts
- no isset
- added safety checks
This is part of #113
=> Split out attribute declaration knowledge to new ReflectionXHPAttribute class

tests/AttributesTest.php
Since `callable` isn't a valid Hack type, get Hack to ignore it. Allows XHP to be included in `assume_php=false` projects.
=> Mark callable as a FIXME

README.textile
I was having a hard time realizing that I have to run Composer through hhvm.  Perhaps an example like this in the Readme would have helped.
=> Add hhvm composer example to readme

.travis.sh, .travis.yml
HHVM 3.19+ are not supported on Ubuntu 14.04, and Travis doesn't support HHVM on 16.04.
=> Use docker for tests

composer.json, composer.lock, src/core/ComposableElement.php
Seeing composer complain about fredemmott/type-assert being abandoned is a bit annoying. I didn't switch to type-assert 2.0 (i.e. change namespaces) because that seems like a bigger deal, but happy to do it if that's considered blocking.
=> Switch from fredemmott/type-assert to hhvm/type-assert.

src/html/tags/l/Link.php
`<link rel="preload" as="font" />` does not work. Need to support `as` attribute.
=> Add 'as' attribute to link tag

src/core/ComposableElement.php, src/core/XHP.php, tests/AttributesTest.php
Adds spread operator support for #188.
It works slightly differently than the internal version because xhp-lib is more pure when it comes to defaults and nulls, so this logic gets to be simplified quite a bit. Also, overriding this is not legal in xhp-lib since there are no extreme legacy use-cases that would need it.
=> add spread operator support to xhp-lib

src/html/tags/s/Script.php
Added `<script integrity="sha512-...">` per the [Subresource Integrity spec](https://www.w3.org/TR/SRI/#the-integrity-attribute)
=> Adding attribute to support the Subresource Integrity spec

.hhconfig, composer.json, composer.lock, tests/AsyncTest.php, tests/AttributesCoercionModeTest.php, tests/AttributesTest.php, tests/BasicsTest.php, tests/ChildRuleTest.php, tests/ContextsTest.php, tests/HackEnumAttributeTest.php, tests/ReflectionTest.php, tests/TestChildFlushing.php, tests/UnsafeInterfacesTest.php, tests/XHPHelpersTest.php
hhast migrate + hackfmt
Also had to change the order of args (i.e. expect(a)->toBeSame(b) to expect(b)->toBeSame(a)) in two expect calls (tests/XHPHelpersTest.php, line 79 + 86) because they have side effects.
=> Migrate assert to expect

src/core/ComposableElement.php, tests/AttributesTest.php
Previously, regular attributes are removed from the DOM when null, but
special attributes would be cast to empty string. This makes them behave
more like regular attributes, so that it's possible to use null as a sentinel
value to remove them from the DOM.
```
<div data-idonotexist={null} />;
```
would render as `<div data-idonotexist=""></div>;`
Unit tests show that now the attribute is removed when null
=> Ensure that special attributes should not render when null

src/core/ComposableElement.php, src/html/XHPBaseHTMLHelpers.php, src/html/XHPHelpers.php
Summary: required for .hhconfig disable_lval_as_an_expression.
Signed-off-by: Arthur Loiret <arthur.loiret@emerton-data.com>
=> Remove usages of lval as an expression.

src/core/ComposableElement.php
I figured that more people have attribute validation turned off.
It is broken (vec is not \HH\Traversable) and turned off by default.
So checking for ReflectionXHPAttribute::IsSpecial() seems like a waste.
If you have validation turned on, there is no difference to you.
If you have it turned off, this just saves you some instructions.
=> Stop reflecting preemptively.

.hhconfig, src/core/ComposableElement.php, src/core/ReflectionXHPAttribute.php, src/core/XHP.php, tests/AttributesCoercionModeTest.php, tests/AttributesTest.php, tests/HackEnumAttributesTest.php
Runtime type validation on XHP properties has been broken for a while. I tried fixing Stringish validation a little while ago, but that was just the first type that had false negatives. `\HH\vec<T>` is not an `\HH\Traversable<T>` according to XHP. There has been discussion about removing the runtime validation all since before I even knew about Hack. It just appears that no one wanted to tackle it, since it was just disabled by default at some point.
My goal was to eliminate false negatives as much as possible. I first removed all runtime typechecking, however, I quickly noticed however that XHP enums are not covered by the typechecker. So, in order to make those attribute types have some value, I kept enum validation for XHP enums. This ended up making XHP enums stronger than Hack enums …
=> Remove runtime userland typechecks

src/children/Any.hack, src/children/AnyNumberOf.hack, src/children/AnyOf.hack, src/children/AtLeastOneOf.hack, src/children/Category.hack, src/children/Constraint.hack, src/children/LeafConstraint.hack, src/children/LegacyConstraintType.hack, src/children/LegacyExpression.hack, src/children/LegacyExpressionType.hack, src/children/None.hack, src/children/OfType.hack, src/children/Optional.hack, src/children/PCData.hack, src/children/QuantifierConstraint.hack, src/children/Sequence.hack, src/children/XHPChildDeclarationConsistencyTrait.hack, src/children/XHPChildDeclarationConsistencyValidation.hack, src/children/XHPChildValidation.hack, src/children/functions.hack, src/core/ComposableElement.php, tests/ChildRuleTest.php
Currently serializes to the same format as HackC, to allow migrating to
the new syntax with no changes to validation.
Some normalization is needed, as HackC emits some overly-complex
structures - e.g. with `$expr = tuple(EXACTLY_ONE, EXPRESSION, $inner_expr)`
can be simplified to `$expr = $inner_expr`.
It is not currently in a form suitable for use - the trait I've added
merely confirms that the two forms of children declaration are
semanticaly equivalent.
I think that's a meaningful first step; if we're happy for this, we can
merge it, start on migration tools, then add an alternative trait to
allow removal of the legacy syntax.
This is very much a draft API; open to a complete rewrite if desired :)
refs #212
=> RFC/Proof-of-concept: Implement children declarations as a trait

src/children/XHPChildDeclarationConsistencyValidation.hack, src/children/XHPChildValidation.hack
This makes it possible to use these traits for HTML tags etc
Test plan:
```
fredemmott@fredemmott-mm1 xhp-lib % ~/code/hhast/bin/hhast-migrate --add-xhp-children-declaration-method src
fredemmott@fredemmott-mm1 xhp-lib % hh_client
No errors!
fredemmott@fredemmott-mm1 xhp-lib % vendor/bin/hacktest tests
...............................................................................S.SSS.S.S.....................SSSS......SS....
Summary: 125 test(s), 113 passed, 0 failed, 12 skipped, 0 error(s).
fredemmott@fredemmott-mm1 xhp-lib % git diff src | gist  -t patch
https://gist.github.com/6dafcf73169756cc80078d2e765ada2c
```
Typechecker fails without this change, as basic HTML elements do not extend `:x:element`
That is with https://github.com/hhvm/hhast/pull/268
=> Child validation: support `x:composable-element`, not just `x:element`

src/core/ComposableElement.hack
Only checked if child validation is enabled.
fixes #212
=> Raise an exception if a legacy child declaration is found

INTERNALS.md, src/children/XHPChildDeclarationConsistencyValidation.hack, src/children/XHPChildValidation.hack, src/core/Element.hack, src/core/Node.hack, src/core/Primitive.hack, src/core/XHPRoot.hack, src/exceptions/InvalidChildrenException.hack, src/html/HasXHPHTMLHelpers.hack, src/html/XHPAttributeClobbering_DEPRECATED.hack, src/html/XHPHTMLHelpers.hack, src/reflection/ReflectionXHPClass.hack, tests/ChildRuleTest.hack
- more DOM-like
- underscores are nasty
- I find the naming confusing: I expected `:x:composable_element` to be
a subtype of `:x:element`, not a supertype.
refs #220
=> Rename :x:composable_element to :x:node

src/html/tags/l/Link.hack
https://html.spec.whatwg.org/multipage/semantics.html#the-link-element
Some of our older non XHP code loads css style sheets on the last line of the body.
This currently throws an `\XHPInvalidChildrenException` upon render with children validation enabled.
=> <link> can be placed in the <body> in phrase and flow contexts

.hhconfig, tests/AttributesTest.hack, tests/TestChildFlushing.hack
#258 electric boogaloo
Github decided to close the PR when I reset the world, since there were no pending commits.
I can't reopen that PR for some reason, even when there are pending commits.
=> Make check_xhp_attribute not emit errors

src/html/singleton.hack, src/html/unescaped_pcdata_element.hack, tests/BasicsTest.hack
The old name for this method was `->stringify()`.
These stragglers did not have an `__Override` on `->stringify()`, so the typechecker could not warn us about this.
Fixes:
`<br/>` now renders as `<br>` again (not `<br></br>`).
`<style>&</style>` now renders as `<style>&</style>` again, (not `<style>&amp;</style>`).
=> Fix stringify() -> stringifyAsync()

src/core/Node.hack, src/core/Primitive.hack, tests/BasicsTest.hack
- The exception messages mentioned methods as string literals.
These did not always match the actual method name.
- The __isRendered flag was not set for primitives.
This might have been intentional.
If it is, revert the changes in primitive.
However, it is strange to allow ->setAttribute() after render on div,
but prohibit it on ui:div.
=> Fix some perceived problems with __isRendered

src/core/Node.hack, tests/BasicsTest.hack
In XHP-4 ->getFirstChild('h1') is going to break.
You need h1::class or "Facebook\...\h1".
Let's encourage the use of reified generics.
They are typechecked and allow us to safely type the return type.
Old methods continue to return XHPChild.
I also spotted an inconsistency with the handling of `''` as a selector.
=> Add safer get___Child methods

src/core/Node.hack, tests/BasicsTest.hack
Now that categories are replaced with interfaces, unneeded - the reified
versions are sufficient.
While I'm here, add docblock
fixes #270
=> Remove string child selectors

src/core/Node.hack, src/html/categories/Category.hack, src/html/categories/Embedded.hack, src/html/categories/Flow.hack, src/html/categories/Heading.hack, src/html/categories/Interactive.hack, src/html/categories/Metadata.hack, src/html/categories/Sectioning.hack, tests/BasicsTest.hack
- add base interface for HTML categories that explicitly extends it
- add unit test for this new functionality
Using `<detail>` and `<script>` as more common classes do not have
the expected categories (#273)
=> Constrain `getFirstChildOfType` etc to `XHPChild`

src/core/Element.hack, src/core/Primitive.hack, src/core/UseAfterRenderException.hack, tests/BasicsTest.hack
thrown deep inside of rendered trees
refers to https://github.com/hhvm/xhp-lib/issues/279#issue-673009008
=> Add an XHPPath to UseAfterRenderExceptions

src/core/Node.hack, src/core/UnsafeAttributeValue_DEPRECATED.hack, src/html/element.hack, tests/UnsafeInterfacesTest.hack
This is almost the same as a unsafe type fixme, except that it also
bypasses runtime enforcement. It will need to be removed before the type
system can be sound.
=> Rename UnsafeAttributeValue to UnsafeAttributeValue_DEPRECATED

composer.json, src/Reflection/ReflectionXHPChildrenDeclaration.hack
This composer.json did not mention that we depended on the hsl.
The hsl came for free with type-assert.
We don't need TypeAssert, since we don't depend on varrayness.
This also improves perf, since we are not spinning in
a loop validating that all elements are mixed, which they always are.
=> Clean up dependencies of xhp-lib

src/core/Node.hack, src/exceptions/InvalidChildrenException.hack, src/html/tags/c/ConditionalComment.hack, src/html/tags/d/Doctype.hack, tests/ChildRuleTest.hack
This docblock mentions was incorrect, because an explicit null would make this method return true.
=> Update incorrect docblock for isAttributeSet

README.md
=> Modernize the README for v4

.gitattributes, .github/workflows/build-and-test.yml, .hhvmconfig.hdf, composer.json, hh_autoload.json, src/Reflection/ReflectionXHPAttribute.hack, src/core/Node.hack, tests/AsyncTest.hack, tests/AttributesTest.hack
The hsl is always built-in.
ext_watchman and HH\Facts are always available.
varray eq vec and darray eq dict is always true.
All legacy arrays have been replaced with Hack arrays.
=> Require hhvm 4.128 and support autoloading with ext_watchman
