MIGRATING.md
src/core.php

Add XHPUnsafeRenderable, XHPAlwaysValidChild, MIGRATING.md

---

src/core.php

All of :x:composable-element::__flushRenderedElement() was specific
to :x:element, however it depended on private members of
:x:composable-element. Made them protected instead and added the usual
prefix.
This makes hack happy even with this diff:
https://gist.github.com/fredemmott/c94a7e9f844b7ae60df6

Refactor :x:element and :x:composable-element

---

src/core.php

Support XHPUnsafeRenderable in renderChild

---

composer.json
composer.lock
tests/AsyncTest.php
tests/BasicsTest.php

Coverage is terrible, but better than nothing :)

Add some unit tests

---

src/core/ComposableElement.php
src/core/ReflectionXHPChildrenDeclaration.php
tests/ChildRuleTest.php

Part of #113 - gets rid of a load of array access, adds safety checks, etc.

Add ReflectionXHPChildrenDeclaration, use it for validation and string conversions

---

src/core/ComposableElement.php
src/core/ReflectionXHPAttribute.php
src/core/ReflectionXHPChildrenDeclaration.php
src/core/ReflectionXHPClass.php
tests/BasicsTest.php
tests/ChildRuleTest.php
tests/ReflectionTest.php

Full reflection

---

README.textile

The first sentence was: XHP is augments the syntax of Hack such that ...

Updated Readme fixing grammar

---

.travis.yml

Has 3.5. 3.7 isn't packaged for their distro, but 3.6 should be available

Tell travis to install the latest release of HHVM

---

src/core/ComposableElement.php
tests/AttributesTest.php

Add support for num and arraykey attributes

---

src/core/ComposableElement.php

Use an empty instance instead of invalid static calls

---

src/core/Element.php
src/core/Primitive.php

replaced with HH\Asio\join()
fixes #170. Tested with 3.15 and nightly

Remove getWaitHandle()->join()

---

src/core/XHPUnsafeAttributeValue.php
src/html/Element.php
tests/UnsafeInterfacesTest.php

add support for XHPUnsafeRenderable in HTML attributes

---

src/core/ComposableElement.php
src/core/XHP.php

These change/disable the mangling, so we need to check for them.

Support namespaces in class2element and element2class

---

src/core/ComposableElement.hack
tests/AttributesTest.hack

Make attribute spread copy data- and aria- attributes

---

tests/AsyncTest.hack

Ran hhast externally, since this project does not have a hhast-lint.json
refs #237

Pass DataProviderTypesLinter

---

README.md

remove redundant comment from readme

---

src/core/Element.hack
src/core/Node.hack
src/core/Primitive.hack
src/core/UseAfterRenderException.hack
tests/BasicsTest.hack

Change the exception type to UseAfterRenderException in place of InvariantException

---

.gitignore
.hhconfig
src/core/Node.hack
src/exceptions/AttributeNotSupportedException.hack
src/exceptions/AttributeRequiredException.hack
src/exceptions/ClassException.hack
src/exceptions/CoreRenderException.hack
src/exceptions/InvalidChildrenException.hack

Dependencies are not yet ready, so CI will fail.

Typecheck with enable_strict_string_concat_interp

---

.github/workflows/build-and-test.yml
src/core/ComposableElement.php
src/core/XHP.php

20.04 is newer than 4.32 and not supported.

Target old ubuntu 18.04 for HHVM 4.32 CI

---

README.md

-Fixed Spelling and Grammar Mistakes

Fixed Grammar Mistakes
